site_name: Correlated Counts
nav:
  - Home: 'index.md'
  - Methods: 'methods.md'
  - Models: 'models.md'
  - Code: 'code.md'
theme: material
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
    - mdx_math
